name: Android Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Force Java 17 environment
        run: |
          # 查找Java 17安装路径
          JAVA17_PATH=$(find /opt/hostedtoolcache -name "java" -type f | grep -E "17|temurin" | head -1 | xargs dirname | xargs dirname)
          echo "Found Java 17 at: $JAVA17_PATH"
          
          # 强制设置环境变量
          export JAVA_HOME="$JAVA17_PATH"
          export PATH="$JAVA_HOME/bin:$PATH"
          
          # 验证
          java -version
          echo "JAVA_HOME: $JAVA_HOME"
          
          # 创建gradle.properties
          echo "org.gradle.java.home=$JAVA_HOME" > gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties

      - name: Build with Gradle
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          PATH: ${{ env.JAVA_HOME }}/bin:${{ env.PATH }}
        run: |
          chmod +x gradlew
          ./gradlew app:assembleRelease --info

      - name: Key base64 to file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'android_key.jks'
          fileDir: '/tmp/.android_key/'
          encodedString: ${{ secrets.ANDROID_KEY_BASE64 }}

      - name: Install apksigner
        run: sudo apt install apksigner

      - name: Sign apk
        env:
          ANDROID_KS_PASS: ${{ secrets.ANDROID_KS_PASS }}
        run: |
          for file in app/build/outputs/apk/release/*.apk; do
            if [[ -f "$file" ]]; then
              filename="${file##*/}"
              echo "Signing ${filename}"
              apksigner sign --v4-signing-enabled false \
                --ks /tmp/.android_key/android_key.jks \
                --ks-pass env:ANDROID_KS_PASS \
                --ks-key-alias ${{ secrets.ANDROID_KEY_ALIAS }} \
                "$file"
            fi
          done

      - name: Upload apk to artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: app/build/outputs/apk/release/*.apk
